# TODO: Those can be removed if/when kustomize supports skipping Helm tests
$patch: delete
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-test-sa
  namespace: grafana-agent
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent-test-cr
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-test-crb
---
$patch: delete
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  name: grafana-agent-test
  namespace: grafana-agent
---
$patch: delete
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: primary-test
  namespace: grafana-agent
---
$patch: delete
apiVersion: v1
kind: Pod
metadata:
  name: grafana-agent-test-probe
  namespace: grafana-agent
